kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-no-sc-specified
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi

