kind: Pod
apiVersion: v1
metadata:
  name: test-pod-using-default-sc
spec:
  containers:
  - name: test-pod-using-default-sc
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/default-sc-applied.txt && exit 0 || exit 1"
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: test-claim-no-sc-specified


