apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-nfs
  name: nginx-nfs
  namespace: default
spec:
  ports:
  - nodePort: 31112 # define or leave it blank (should be 30000-32767)
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-nfs
  sessionAffinity: None
  type: LoadBalancer
